---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: "{{ elasticsearch_key }}"
    state: present

- name: Add Elasticsearch repository.
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644    

- name: Install Elasticsearch.
  yum: pkg=elasticsearch state=present
