---
- name: Add Elasticsearch apt key.
  apt_key:
    url: "{{ elasticsearch_key }}"
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb {{ elasticsearch_debian_repository }} stable main'
    state: present
    update_cache: true

- name: Install Elasticsearch.
  apt: pkg=elasticsearch state=present